databases:
  vastbase:
    nexus:
      domain: "http://172.16.107.3:8081"
      username: "package"
      password: "6uVXs5P3N9RgaBMR"
      repository: "vastbase-software"
      package:
        psu:
          path_template: "安装包/VastbaseG100/G100打穿包/{version_code}/{psu}"
          file_pattern: "Vastbase-G100-{major}.{minor}_Build{build}.*-Linux-x86_64-no_mot-.*\\.tar\\.gz"
        build:
          keyword_template: "Vastbase-G100-{major}.{minor}_Build{build}_{build_num}-Linux-x86_64-no_mot-"
    defaults:
      base_image: "vastbase-g100-base:v0.0.1"
      port: 5432
      adapter: "VastbaseAdapter"
      username: "vbmcp"
      password: "Vastbase@123"
      database: "postgres"
      privileged: true
      env:
        VB_USERNAME: "vbmcp"
        VB_PASSWORD: "Vastbase@123"
        USER_PRIVILEGE: "sysadmin"
    versions:
      "3.0.9":
        psu: "01"
        port: 5432
        adapter: "VastbaseAdapter"
        username: "vbmcp"
        password: "Vastbase@123"
        database: "postgres"
        privileged: true
        prewarm: true
        env:
          VB_USERNAME: "vbmcp"
          VB_PASSWORD: "Vastbase@123"
          USER_PRIVILEGE: "sysadmin"
      "3.0.8":
        psu: "4"
        port: 5432
        adapter: "VastbaseAdapter"
        username: "vbmcp"
        password: "Vastbase@123"
        database: "postgres"
        privileged: true
        prewarm: true
        env:
          VB_USERNAME: "vbmcp"
          VB_PASSWORD: "Vastbase@123"
          USER_PRIVILEGE: "sysadmin"
      "2.2.15":
        psu: "11"
        port: 5432
        adapter: "VastbaseAdapter"
        username: "vbmcp"
        password: "Vastbase@123"
        database: "postgres"
        privileged: true
        prewarm: true
        env:
          VB_USERNAME: "vbmcp"
          VB_PASSWORD: "Vastbase@123"
          USER_PRIVILEGE: "sysadmin"
  kingbase:
    versions:
      "v8":
        image: "kingbase/kdb:V8"
        port: 54321
        adapter: "KingbaseAdapter"
        username: "SYSTEM"
        password: "password"
        database: "TEST"
        env:
          NEED_START: "yes"
          DB_USER: "SYSTEM"
          DB_PASSWORD: "password"
          ENABLE_CI: "yes"
      "v9":
        image: "kingbase_v009r001c010b0004_single_x86:v1"
        port: 54321
        adapter: "KingbaseAdapter"
        username: "system"
        password: "12345678ab"
        database: "test"
        env:
          NEED_START: "yes"
          DB_USER: "system"
          DB_PASSWORD: "12345678ab"
          ENABLE_CI: "yes"

  postgresql:
    versions:
      "12":
        image: "postgres:12"
        port: 5432
        adapter: "PostgreSQLAdapter"
        username: "postgres"
        password: "postgres"
        database: "postgres"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
      "13":
        image: "postgres:13"
        port: 5432
        adapter: "PostgreSQLAdapter"
        username: "postgres"
        password: "postgres"
        database: "postgres"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
      "14":
        image: "postgres:14"
        port: 5432
        adapter: "PostgreSQLAdapter"
        username: "postgres"
        password: "postgres"
        database: "postgres"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"

  oracle:
    versions:
      "11c":
        image: "gvenzl/oracle-xe:11-slim"
        port: 1521
        adapter: "OracleAdapter"
        username: "SYSTEM"
        password: "oracle"
        database: "XE"
        env:
          ORACLE_PASSWORD: "oracle"

      "12c":
        image: "gvenzl/oracle-xe:12-slim"
        port: 1521
        adapter: "OracleAdapter"
        username: "SYSTEM"
        password: "oracle"
        database: "XE"
        env:
          ORACLE_PASSWORD: "oracle"

      "18c":
        image: "gvenzl/oracle-xe:18-slim"
        port: 1521
        adapter: "OracleAdapter"
        username: "SYSTEM"
        password: "oracle"
        database: "XE"
        env:
          ORACLE_PASSWORD: "oracle"

      # "19c":
      #   image: "registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c"
      #   port: 1521
      #   adapter: "OracleAdapter"
      #   username: "system"
      #   password: "Oracle@123"
      #   database: "ORCLPDB"
      #   env:
      #     ORACLE_SID: "ORCLCDB"
      #     ORACLE_PDB: "ORCLPDB"
      #     ORACLE_PWD: "Oracle@123"
      "21c":
        image: "gvenzl/oracle-xe:21-slim"
        port: 1521
        adapter: "OracleAdapter"
        username: "SYSTEM"
        password: "oracle"
        database: "XE"
        env:
          ORACLE_PASSWORD: "oracle"


  mysql:
    versions:
      "5.6":
        image: "mysql:5.6"
        port: 3306
        adapter: "MySQLAdapter"
        username: "root"
        password: "root123"
        database: "test"
        command: "--default-authentication-plugin=mysql_native_password --skip-name-resolve"
        env:
          MYSQL_ROOT_PASSWORD: "root123"
          MYSQL_DATABASE: "test"
          MYSQL_ROOT_HOST: "%"
      "5.7":
        image: "mysql:5.7"
        port: 3306
        adapter: "MySQLAdapter"
        username: "root"
        password: "root123"
        database: "test"
        command: "--default-authentication-plugin=mysql_native_password --skip-name-resolve"
        env:
          MYSQL_ROOT_PASSWORD: "root123"
          MYSQL_DATABASE: "test"
          MYSQL_ROOT_HOST: "%"
      "8.0":
        image: "mysql:8.0"
        port: 3306
        adapter: "MySQLAdapter"
        username: "root"
        password: "root123"
        database: "test"
        command: "--default-authentication-plugin=mysql_native_password --skip-name-resolve"
        env:
          MYSQL_ROOT_PASSWORD: "root123"
          MYSQL_DATABASE: "test"
          MYSQL_ROOT_HOST: "%"

  sqlserver:
    versions:
      "2017":
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        port: 1433
        adapter: "SqlServerAdapter"
        username: "sa"
        password: "Mssql@123"
        database: "master"
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Mssql@123"
      "2019":
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        port: 1433
        adapter: "SqlServerAdapter"
        username: "sa"
        password: "Mssql@123"
        database: "master"
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Mssql@123"
